#!/bin/bash
set -euo pipefail

IMAGE_NAME=${1:-brimstone/centos}
# stolen from https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1
VCS_REF="$(git rev-parse --short HEAD)"
BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

for f in Dockerfile.*; do
	v="${f##Dockerfile.}"
	docker build -f "$f" \
		--build-arg VCS_REF="${VCS_REF}" \
		--build-arg BUILD_DATE="${BUILD_DATE}" \
			-t "$IMAGE_NAME:$v" .
	docker tag "$IMAGE_NAME:$v" "$IMAGE_NAME:${v%.*}"
done

latest="$(ls Dockerfile.* | sort -r | head -n 1)"
latest="${latest##Dockerfile.}"
docker tag "$IMAGE_NAME:$latest" "$IMAGE_NAME:latest"
